In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Classes
### Econ 524

Classes are a way for the programmer to define their own types.  

Classes can have "attributes", which are essentially variables associated with an instance of a class.

Classes can have "methods", which are essentially functions associated with an instance of a class.

If the variable x is an instance of some class and the class has attributes a and b, then you can reference those attributes as x.a and x.b.

Similarly, if the class has methods f and g, then you can call those methods x.f() and x.g().

We have already seen examples of using attributes and methods of classes at various points this quarter. 

For example, DataFrame is an example of a class.

In [6]:
import pandas as pd

d = pd.DataFrame({"num":  [1,2,3,4,5], "let":  ["a","b","c","d","e"]})
d

# examples of attributes of the DataFrame class
d.values
d.index
d.columns

# examples of methods of the DataFrame class
e=d.sort_values("num",ascending=False)
e
e.reset_index()

   num let
0    1   a
1    2   b
2    3   c
3    4   d
4    5   e

array([[1, 'a'],
       [2, 'b'],
       [3, 'c'],
       [4, 'd'],
       [5, 'e']], dtype=object)

RangeIndex(start=0, stop=5, step=1)

Index(['num', 'let'], dtype='object')

   num let
4    5   e
3    4   d
2    3   c
1    2   b
0    1   a

   index  num let
0      4    5   e
1      3    4   d
2      2    3   c
3      1    2   b
4      0    1   a

The names of attributes do not conflict with global variables of the same name.

In [3]:
values = [6,4,2]
values
d.values

[6, 4, 2]

array([[1, 'a'],
       [2, 'b'],
       [3, 'c'],
       [4, 'd'],
       [5, 'e']], dtype=object)

The names of methods do not conflict with functions of the same name.

In [4]:
def sort_values(x):
    return 4

e.sort_values("num")
sort_values("num")

   num let
0    1   a
1    2   b
2    3   c
3    4   d
4    5   e

4

## Functions vs. Methods

Compare how we called concat or read_csv (functions defined in pandas) to how we called reset_index or drop (methods of the class DataFrame).

Methods typically do something related to the calling object.

## How to define a class

You define a class using the keyword "class" and providing a name.  This doesn't create an object of the class, it just defines a class that you can later create an object for (similar to how def for functions doesn't call the function, it just defines a function that can be called later).

Indented and immediately following the class definition, you can define attributes and methods for the class.  In the example below, we define a class names Point that has two attributes, x and y, both of which will be initialized to value 0 whenever a Point object is created.  This example has no methods (see below for example with methods).

To create a Point object, we call the function Point().

In [8]:
class Point:
    x=0
    y=0



p = Point()
p
type(p)
p.x
p.y

p.x = 1
p.y = 2
p.z = 3

p.x
p.y
p.z

__main__.Point

0

0

1

2

3

## How to define methods

You can define methods for a class using "def" as part of the class definition, indenting on the lines after "class".

When defining a method, the first argument to the method should be "self" which is the way you reference the object itself from within the method.

However, when calling the method, you omit this argument; it will automatically define self to be the calling object.

You can optionally define a method for the class "\_\_init__".  This method will be automatically called every time you create a new object of this class.

In the example below, we use the \_\_init__ method to define the x and y attributes, which is preferable to the previous example.  By having default values of 0 for x and y in the method, we get the same default behavior as in the previous example but we offer the flexibility of providing other x and y values when creating the Point object.

In [28]:
class Point:
    def __init__(self,x=0,y=0):
        self.x=x
        self.y=y

p = Point()
p
p.x
p.y

p2 = Point(3,4)
p2
p2.x
p2.y

0

0

3

4

In [5]:
class Point:
    def __init__(self,x=0,y=0):
        self.x=x
        self.y=y
    
    def dist(self):
        import math
        return math.sqrt(self.x**2 + self.y**2)

p = Point()
p2 = Point(3,4)

p.dist()

p2.dist()

print(p)

0.0

5.0

<__main__.Point object at 0x000001F4CFE205D0>

You can optionally define the \_\_str__ method, which is called if you pass an instance of the class to the print function.  The \_\_str__ method creates a text representation of the class.

In [8]:
class Point:
    def __init__(self,x=0,y=0):
        self.x=x
        self.y=y
        
    def __str__(self):
        return "("+str(self.x)+","+str(self.y)+")"
    
    def dist(self):
        import math
        return math.sqrt(self.x**2 + self.y**2)
    
p = Point()
p
print(p)
print(Point(4,3))

(0,0)
(4,3)

You can also overload operators in Python so that they work with user-defined classes.  

For example, if you include a method called \_\_add__ in your class, it will overload the + operator.

object.\_\_add__(self, other)

object.\_\_sub__(self, other)

object.\_\_mul__(self, other)

object.\_\_matmul__(self, other)

object.\_\_truediv__(self, other)

object.\_\_floordiv__(self, other)

object.\_\_mod__(self, other)

object.\_\_pow__(self, other[, modulo])

object.\_\_lshift__(self, other)

object.\_\_rshift__(self, other)

object.\_\_and__(self, other)

object.\_\_xor__(self, other)

object.\_\_or__(self, other)¶

+, -, *, @, /, //, %, **, <<, >>, &, ^, |

In [32]:
class Point:
    def __init__(self,x=0,y=0):
        self.x=x
        self.y=y
        
    def __str__(self):
        return "("+str(self.x)+","+str(self.y)+")"
    
    def dist(self):
        import math
        return math.sqrt(self.x**2 + self.y**2)
    
    def __add__(self, other):
        return Point(self.x+other.x,self.y+other.y)

p = Point(1,2)
p2 = Point(4,-3)

p+p2
print(p+p2)

(5,-1)

In [10]:
import copy
p=Point()
pnew=copy.copy(p)
p
p.x
p.y
pnew
pnew.x
pnew.y

0

0

0

0

In [11]:
def add_to_point(p):
    p.x=p.x+1
    p.y=p.y+1
    return p

q=add_to_point(pnew)
q.x
q.y
pnew.x
pnew.y

1

1

1

1

In [12]:
class Point:
    def __init__(self,x=0,y=0):
        self.x=x
        self.y=y
        
    def __str__(self):
        return "("+str(self.x)+","+str(self.y)+")"
    
    def dist(self):
        import math
        return math.sqrt(self.x**2 + self.y**2)
    
    def __add__(self, other):
        return Point(self.x+other.x,self.y+other.y)
    
    def copy(self):
        import copy
        return copy.deepcopy(self)  #deepcopy copies the object and all objects the object references as attributes


def add_to_point(p):
    q=p.copy()
    q.x=q.x+1
    q.y=q.y+1
    return q

pnew = Point(6,7)

q=add_to_point(pnew)
q.x
q.y
pnew.x
pnew.y

7

8

6

7