In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Data Import (XML)

## XML

XML is a format for storing data to pass between applications.

XML files are made up of “tags” (which may have “attributes”).  The data provided in tags and attributes is application-specific.

XML files are a “text” format.  You can view them in a regular text editor (like Notepad on Windows) and see all the tags.

# Beautiful Soup

Beautiful soup is a package in python that provides functions to easily parse XML files and extract relevant information.

Note:  It can also be used to parse and extract information from HTML files.  This is useful for webscraping - i.e. importing data in Python from web pages.

We will import beautiful soup and also a package to help download/read XML files from the web.

In [5]:
from bs4 import BeautifulSoup
import urllib.request as url
import pandas as pd

The BeautifulSoup class takes an XML file as input and creates an object with methods to parse the XML.

Conceptually, it is based on a hierarchical view of XML (example shown below).

Each tag has a parent tag, zero or more children tags, zero or more attributes, and possibly an untagged child (i.e. string text).

In the example here, the data is for an inventory of CD's and so there is a tag "CD" to identify a CD.  Each CD tag has children for the following fields:  title, artist, price, and year.  The CD tag has an attribute named id that provides a unique integer id for each cd.

In this application, the data being represented could easily have been pulled from a database and it can easily be represented as a dataframe where a CD tag reprents a row/record and where title/artist/price/year are the fields/columns.

```text
<CATALOG><CD id="1"><TITLE>Empire Burlesque</TITLE><ARTIST>Bob Dylan</ARTIST><PRICE>10.90</PRICE><YEAR>1985</YEAR></CD><CD id="2"><TITLE>Hide your heart</TITLE><ARTIST>Bonnie Tyler</ARTIST><PRICE>9.90</PRICE><YEAR>1988</YEAR></CD><CD id="3"><TITLE>Greatest Hits</TITLE><ARTIST>Dolly Parton</ARTIST><PRICE>9.90</PRICE><YEAR>1982</YEAR></CD><CD id="4"><TITLE>Still got the blues</TITLE><ARTIST>Gary Moore</ARTIST><PRICE>10.20</PRICE><YEAR>1990</YEAR></CD><CD id="5"><TITLE>Eros</TITLE><ARTIST>Eros Ramazzotti</ARTIST><PRICE>9.90</PRICE><YEAR>1997</YEAR></CD><CD id="6"><TITLE>One night only</TITLE><ARTIST>Bee Gees</ARTIST><PRICE>10.90</PRICE><YEAR>1998</YEAR></CD><CD id="7"><TITLE>Sylvias Mother</TITLE><ARTIST>Dr.Hook</ARTIST><PRICE>8.10</PRICE><YEAR>1973</YEAR></CD><CD id="8"><TITLE>Maggie May</TITLE><ARTIST>Rod Stewart</ARTIST><PRICE>8.50</PRICE><YEAR>1990</YEAR></CD><CD id="9"><TITLE>Romanza</TITLE><ARTIST>Andrea Bocelli</ARTIST><PRICE>10.80</PRICE><YEAR>1996</YEAR></CD><CD id="10"><TITLE>When a man loves a woman</TITLE><ARTIST>Percy Sledge</ARTIST><PRICE>8.70</PRICE><YEAR>1987</YEAR></CD><CD id="11"><TITLE>Black angel</TITLE><ARTIST>Savage Rose</ARTIST><PRICE>10.90</PRICE><YEAR>1995</YEAR></CD><CD id="12"><TITLE>1999 Grammy Nominees</TITLE><ARTIST>Many</ARTIST><PRICE>10.20</PRICE><YEAR>1999</YEAR></CD><CD id="13"><TITLE>For the good times</TITLE><ARTIST>Kenny Rogers</ARTIST><PRICE>8.70</PRICE><YEAR>1995</YEAR></CD><CD id="14"><TITLE>Big Willie style</TITLE><ARTIST>Will Smith</ARTIST><PRICE>9.90</PRICE><YEAR>1997</YEAR></CD><CD id="15"><TITLE>Tupelo Honey</TITLE><ARTIST>Van Morrison</ARTIST><PRICE>8.20</PRICE><YEAR>1971</YEAR></CD><CD id="16"><TITLE>Soulsville</TITLE><ARTIST>Jorn Hoel</ARTIST><PRICE>7.90</PRICE><YEAR>1996</YEAR></CD><CD id="17"><TITLE>The very best of</TITLE><ARTIST>Cat Stevens</ARTIST><PRICE>8.90</PRICE><YEAR>1990</YEAR></CD><CD id="18"><TITLE>Stop</TITLE><ARTIST>Sam Brown</ARTIST><PRICE>8.90</PRICE><YEAR>1988</YEAR></CD><CD id="19"><TITLE>Bridge of Spies</TITLE><ARTIST>T'Pau</ARTIST><PRICE>7.90</PRICE><YEAR>1987</YEAR></CD><CD id="20"><TITLE>Private Dancer</TITLE><ARTIST>Tina Turner</ARTIST><PRICE>8.90</PRICE><YEAR>1983</YEAR></CD><CD id="21"><TITLE>Midt om natten</TITLE><ARTIST>Kim Larsen</ARTIST><PRICE>7.80</PRICE><YEAR>1983</YEAR></CD><CD id="22"><TITLE>Pavarotti Gala Concert</TITLE><ARTIST>Luciano Pavarotti</ARTIST><PRICE>9.90</PRICE><YEAR>1991</YEAR></CD><CD id="23"><TITLE>The dock of the bay</TITLE><ARTIST>Otis Redding</ARTIST><PRICE>7.90</PRICE><YEAR>1987</YEAR></CD><CD id="24"><TITLE>Picture book</TITLE><ARTIST>Simply Red</ARTIST><PRICE>7.20</PRICE><YEAR>1985</YEAR></CD><CD id="25"><TITLE>Red</TITLE><ARTIST>The Communards</ARTIST><PRICE>7.80</PRICE><YEAR>1987</YEAR></CD><CD id="26"><TITLE>Unchain my heart</TITLE><ARTIST>Joe Cocker</ARTIST><PRICE>8.20</PRICE><YEAR>1987</YEAR></CD></CATALOG>
```

![Hello](xml_example.png)

The code below creates the BeautifulSoup object.  

We specify that the file is "xml"  (vs. alternative of "html.parser" for parsing HTML files/web scraping)  

Also note that I am opening a local file so use "file:..." but I could specify a web address "http://..." when defining urlstring

In [24]:
urlstring = "file:xml_example2025.txt"    
req = url.Request(urlstring)    
file = url.urlopen(req)
soup = BeautifulSoup(file,"xml")

The BeautifulSoup object (i.e. soup) contains a single child Tag with name “CATALOG”

The CATALOG Tag object has a parent of type BeautifulSoup

The CATALOG Tag has 26 children, one for each CD in the catalog.  Each of these children is of type Tag.

In [30]:
type(soup)

len(soup.contents)

soup.contents

bs4.BeautifulSoup

1

[<CATALOG><CD id="1"><TITLE>Empire Burlesque</TITLE><ARTIST>Bob Dylan</ARTIST><PRICE>10.90</PRICE><YEAR>1985</YEAR></CD><CD id="2"><TITLE>Hide your heart</TITLE><ARTIST>Bonnie Tyler</ARTIST><PRICE>9.90</PRICE><YEAR>1988</YEAR></CD><CD id="3"><TITLE>Greatest Hits</TITLE><ARTIST>Dolly Parton</ARTIST><PRICE>9.90</PRICE><YEAR>1982</YEAR></CD><CD id="4"><TITLE>Still got the blues</TITLE><ARTIST>Gary Moore</ARTIST><PRICE>10.20</PRICE><YEAR>1990</YEAR></CD><CD id="5"><TITLE>Eros</TITLE><ARTIST>Eros Ramazzotti</ARTIST><PRICE>9.90</PRICE><YEAR>1997</YEAR></CD><CD id="6"><TITLE>One night only</TITLE><ARTIST>Bee Gees</ARTIST><PRICE>10.90</PRICE><YEAR>1998</YEAR></CD><CD id="7"><TITLE>Sylvias Mother</TITLE><ARTIST>Dr.Hook</ARTIST><PRICE>8.10</PRICE><YEAR>1973</YEAR></CD><CD id="8"><TITLE>Maggie May</TITLE><ARTIST>Rod Stewart</ARTIST><PRICE>8.50</PRICE><YEAR>1990</YEAR></CD><CD id="9"><TITLE>Romanza</TITLE><ARTIST>Andrea Bocelli</ARTIST><PRICE>10.80</PRICE><YEAR>1996</YEAR></CD><CD id="10"><TITLE>When a man loves a woman</TITLE><ARTIST>Percy Sledge</ARTIST><PRICE>8.70</PRICE><YEAR>1987</YEAR></CD><CD id="11"><TITLE>Black angel</TITLE><ARTIST>Savage Rose</ARTIST><PRICE>10.90</PRICE><YEAR>1995</YEAR></CD><CD id="12"><TITLE>1999 Grammy Nominees</TITLE><ARTIST>Many</ARTIST><PRICE>10.20</PRICE><YEAR>1999</YEAR></CD><CD id="13"><TITLE>For the good times</TITLE><ARTIST>Kenny Rogers</ARTIST><PRICE>8.70</PRICE><YEAR>1995</YEAR></CD><CD id="14"><TITLE>Big Willie style</TITLE><ARTIST>Will Smith</ARTIST><PRICE>9.90</PRICE><YEAR>1997</YEAR></CD><CD id="15"><TITLE>Tupelo Honey</TITLE><ARTIST>Van Morrison</ARTIST><PRICE>8.20</PRICE><YEAR>1971</YEAR></CD><CD id="16"><TITLE>Soulsville</TITLE><ARTIST>Jorn Hoel</ARTIST><PRICE>7.90</PRICE><YEAR>1996</YEAR></CD><CD id="17"><TITLE>The very best of</TITLE><ARTIST>Cat Stevens</ARTIST><PRICE>8.90</PRICE><YEAR>1990</YEAR></CD><CD id="18"><TITLE>Stop</TITLE><ARTIST>Sam Brown</ARTIST><PRICE>8.90</PRICE><YEAR>1988</YEAR></CD><CD id="19"><TITLE>Bridge of Spies</TITLE><ARTIST>T'Pau</ARTIST><PRICE>7.90</PRICE><YEAR>1987</YEAR></CD><CD id="20"><TITLE>Private Dancer</TITLE><ARTIST>Tina Turner</ARTIST><PRICE>8.90</PRICE><YEAR>1983</YEAR></CD><CD id="21"><TITLE>Midt om natten</TITLE><ARTIST>Kim Larsen</ARTIST><PRICE>7.80</PRICE><YEAR>1983</YEAR></CD><CD id="22"><TITLE>Pavarotti Gala Concert</TITLE><ARTIST>Luciano Pavarotti</ARTIST><PRICE>9.90</PRICE><YEAR>1991</YEAR></CD><CD id="23"><TITLE>The dock of the bay</TITLE><ARTIST>Otis Redding</ARTIST><PRICE>7.90</PRICE><YEAR>1987</YEAR></CD><CD id="24"><TITLE>Picture book</TITLE><ARTIST>Simply Red</ARTIST><PRICE>7.20</PRICE><YEAR>1985</YEAR></CD><CD id="25"><TITLE>Red</TITLE><ARTIST>The Communards</ARTIST><PRICE>7.80</PRICE><YEAR>1987</YEAR></CD><CD id="26"><TITLE>Unchain my heart</TITLE><ARTIST>Joe Cocker</ARTIST><PRICE>8.20</PRICE><YEAR>1987</YEAR></CD></CATALOG>]

The CATALOG Tag object has a parent of type BeautifulSoup

The CATALOG Tag has 26 children, one for each CD in the catalog.  Each of these children is of type Tag.

In [40]:

ctag = soup.contents[0]
type(ctag)
ctag.name
ctag.attrs
ctag.parent is soup
type(ctag.parent)
len(ctag.contents)
ctag.contents

bs4.element.Tag

'CATALOG'

{}

True

bs4.BeautifulSoup

26

[<CD id="1"><TITLE>Empire Burlesque</TITLE><ARTIST>Bob Dylan</ARTIST><PRICE>10.90</PRICE><YEAR>1985</YEAR></CD>,
 <CD id="2"><TITLE>Hide your heart</TITLE><ARTIST>Bonnie Tyler</ARTIST><PRICE>9.90</PRICE><YEAR>1988</YEAR></CD>,
 <CD id="3"><TITLE>Greatest Hits</TITLE><ARTIST>Dolly Parton</ARTIST><PRICE>9.90</PRICE><YEAR>1982</YEAR></CD>,
 <CD id="4"><TITLE>Still got the blues</TITLE><ARTIST>Gary Moore</ARTIST><PRICE>10.20</PRICE><YEAR>1990</YEAR></CD>,
 <CD id="5"><TITLE>Eros</TITLE><ARTIST>Eros Ramazzotti</ARTIST><PRICE>9.90</PRICE><YEAR>1997</YEAR></CD>,
 <CD id="6"><TITLE>One night only</TITLE><ARTIST>Bee Gees</ARTIST><PRICE>10.90</PRICE><YEAR>1998</YEAR></CD>,
 <CD id="7"><TITLE>Sylvias Mother</TITLE><ARTIST>Dr.Hook</ARTIST><PRICE>8.10</PRICE><YEAR>1973</YEAR></CD>,
 <CD id="8"><TITLE>Maggie May</TITLE><ARTIST>Rod Stewart</ARTIST><PRICE>8.50</PRICE><YEAR>1990</YEAR></CD>,
 <CD id="9"><TITLE>Romanza</TITLE><ARTIST>Andrea Bocelli</ARTIST><PRICE>10.80</PRICE><YEAR>1996</YEAR></CD>,
 <CD id="10"><TITLE>When a man loves a woman</TITLE><ARTIST>Percy Sledge</ARTIST><PRICE>8.70</PRICE><YEAR>1987</YEAR></CD>,
 <CD id="11"><TITLE>Black angel</TITLE><ARTIST>Savage Rose</ARTIST><PRICE>10.90</PRICE><YEAR>1995</YEAR></CD>,
 <CD id="12"><TITLE>1999 Grammy Nominees</TITLE><ARTIST>Many</ARTIST><PRICE>10.20</PRICE><YEAR>1999</YEAR></CD>,
 <CD id="13"><TITLE>For the good times</TITLE><ARTIST>Kenny Rogers</ARTIST><PRICE>8.70</PRICE><YEAR>1995</YEAR></CD>,
 <CD id="14"><TITLE>Big Willie style</TITLE><ARTIST>Will Smith</ARTIST><PRICE>9.90</PRICE><YEAR>1997</YEAR></CD>,
 <CD id="15"><TITLE>Tupelo Honey</TITLE><ARTIST>Van Morrison</ARTIST><PRICE>8.20</PRICE><YEAR>1971</YEAR></CD>,
 <CD id="16"><TITLE>Soulsville</TITLE><ARTIST>Jorn Hoel</ARTIST><PRICE>7.90</PRICE><YEAR>1996</YEAR></CD>,
 <CD id="17"><TITLE>The very best of</TITLE><ARTIST>Cat Stevens</ARTIST><PRICE>8.90</PRICE><YEAR>1990</YEAR></CD>,
 <CD id="18"><TITLE>Stop</TITLE><ARTIST>Sam Brown</ARTIST><PRICE>8.90</PRICE><YEAR>1988</YEAR></CD>,
 <CD id="19"><TITLE>Bridge of Spies</TITLE><ARTIST>T'Pau</ARTIST><PRICE>7.90</PRICE><YEAR>1987</YEAR></CD>,
 <CD id="20"><TITLE>Private Dancer</TITLE><ARTIST>Tina Turner</ARTIST><PRICE>8.90</PRICE><YEAR>1983</YEAR></CD>,
 <CD id="21"><TITLE>Midt om natten</TITLE><ARTIST>Kim Larsen</ARTIST><PRICE>7.80</PRICE><YEAR>1983</YEAR></CD>,
 <CD id="22"><TITLE>Pavarotti Gala Concert</TITLE><ARTIST>Luciano Pavarotti</ARTIST><PRICE>9.90</PRICE><YEAR>1991</YEAR></CD>,
 <CD id="23"><TITLE>The dock of the bay</TITLE><ARTIST>Otis Redding</ARTIST><PRICE>7.90</PRICE><YEAR>1987</YEAR></CD>,
 <CD id="24"><TITLE>Picture book</TITLE><ARTIST>Simply Red</ARTIST><PRICE>7.20</PRICE><YEAR>1985</YEAR></CD>,
 <CD id="25"><TITLE>Red</TITLE><ARTIST>The Communards</ARTIST><PRICE>7.80</PRICE><YEAR>1987</YEAR></CD>,
 <CD id="26"><TITLE>Unchain my heart</TITLE><ARTIST>Joe Cocker</ARTIST><PRICE>8.20</PRICE><YEAR>1987</YEAR></CD>]

All of the CD tag objects have the same parent, which is the CATALOG tag.

Each CD tag has four children, all of type tag (one with name "TITLE", one with name "ARTIST", one with name "PRICE", and one with name "YEAR".

Each CD tag has an attribute (here, I am referring to an XML attribute) that is the unique id of the CD.

To access the XML attributes of a tag, use attrs (Python attribute of Tag object).  attrs is a dictionary that maps each XML attribute to value.

In this example, there is only one XML attribute named "id", so dictionary has a single key-value pair with key "id"

In [42]:
cdtag = ctag.contents[0]

len(cdtag.contents)
cdtag.contents
cdtag.attrs

4

[<TITLE>Empire Burlesque</TITLE>,
 <ARTIST>Bob Dylan</ARTIST>,
 <PRICE>10.90</PRICE>,
 <YEAR>1985</YEAR>]

{'id': '1'}

In [66]:
cdtag.attrs["id"]
int(cdtag.attrs["id"])

'1'

1

In [46]:
ttag=cdtag.contents[0]
atag = cdtag.contents[1]
ptag = cdtag.contents[2]
ytag = cdtag.contents[3]

ttag.parent is cdtag
atag.parent is cdtag
ptag.parent is cdtag
ytag.parent is cdtag

True

True

True

True

When there is text in between the tag brackets, that text will be of type NavigableString.

In this example, the Title tag has only one child of type NavigableString (in fact, all leaf nodes in this XML file have a single child of type NavigableSting).

You can access this string in one of two ways.

1. The Tag object has a string attribute which equals the value of the NavigableString child.
2. You can refer to the NavigableString child directly

See below for examples of both ways.

In [57]:
ttag.name
ttag.contents
ttag.string
type(ttag.contents[0])
ttag.contents[0]

'TITLE'

['Empire Burlesque']

'Empire Burlesque'

bs4.element.NavigableString

'Empire Burlesque'

Similarly, we can get the artist, price, and year:

In [59]:
atag.string
ptag.string
ytag.string

'Bob Dylan'

'10.90'

'1985'

To extract all data into dataframe:

We iterate over every child of CATALOG (outer loop).  Each CD tag has a child for each column.  The column name is the tag name.   We create a dictionary that maps tag name to tag value for each child of the CD tag (the inner loop).  Then we append the dictionary to our data frame.

In [77]:
xmldf = pd.DataFrame()
catalog=soup.contents[0]
for i in range(len(catalog.contents)):
    row=catalog.contents[i]
    cells = row.contents
    rowdict = {"id": int(row.attrs["id"])}
    for j in range(len(cells)):
        rowdict[cells[j].name] = cells[j].string
    xmldf=pd.concat([xmldf,pd.DataFrame(rowdict,index=pd.Index([0]))],ignore_index=True)
    
xmldf

    id                     TITLE             ARTIST  PRICE  YEAR
0    1          Empire Burlesque          Bob Dylan  10.90  1985
1    2           Hide your heart       Bonnie Tyler   9.90  1988
2    3             Greatest Hits       Dolly Parton   9.90  1982
3    4       Still got the blues         Gary Moore  10.20  1990
4    5                      Eros    Eros Ramazzotti   9.90  1997
5    6            One night only           Bee Gees  10.90  1998
6    7            Sylvias Mother            Dr.Hook   8.10  1973
7    8                Maggie May        Rod Stewart   8.50  1990
8    9                   Romanza     Andrea Bocelli  10.80  1996
9   10  When a man loves a woman       Percy Sledge   8.70  1987
10  11               Black angel        Savage Rose  10.90  1995
11  12      1999 Grammy Nominees               Many  10.20  1999
12  13        For the good times       Kenny Rogers   8.70  1995
13  14          Big Willie style         Will Smith   9.90  1997
14  15              Tupelo Honey       Van Morrison   8.20  1971
15  16                Soulsville          Jorn Hoel   7.90  1996
16  17          The very best of        Cat Stevens   8.90  1990
17  18                      Stop          Sam Brown   8.90  1988
18  19           Bridge of Spies              T'Pau   7.90  1987
19  20            Private Dancer        Tina Turner   8.90  1983
20  21            Midt om natten         Kim Larsen   7.80  1983
21  22    Pavarotti Gala Concert  Luciano Pavarotti   9.90  1991
22  23       The dock of the bay       Otis Redding   7.90  1987
23  24              Picture book         Simply Red   7.20  1985
24  25                       Red     The Communards   7.80  1987
25  26          Unchain my heart         Joe Cocker   8.20  1987

In the above code, all data are strings (except for id which I coerced to int).  We could rewrite the code to coerce the price to float and the year to int.

In [74]:
xmldf = pd.DataFrame()
catalog=soup.contents[0]
for i in range(len(catalog.contents)):
    row=catalog.contents[i]
    cells = row.contents
    rowdict = {"id": int(row.attrs["id"])}
    for j in range(len(cells)):
        if cells[j].name=="PRICE":
            rowdict[cells[j].name] = float(cells[j].string)
        elif cells[j].name=="YEAR":
            rowdict[cells[j].name] = int(cells[j].string)
        else:
            rowdict[cells[j].name] = cells[j].string
    xmldf=pd.concat([xmldf,pd.DataFrame(rowdict,index=pd.Index([0]))],ignore_index=True)
    
xmldf

    id                     TITLE             ARTIST  PRICE  YEAR
0    1          Empire Burlesque          Bob Dylan   10.9  1985
1    2           Hide your heart       Bonnie Tyler    9.9  1988
2    3             Greatest Hits       Dolly Parton    9.9  1982
3    4       Still got the blues         Gary Moore   10.2  1990
4    5                      Eros    Eros Ramazzotti    9.9  1997
5    6            One night only           Bee Gees   10.9  1998
6    7            Sylvias Mother            Dr.Hook    8.1  1973
7    8                Maggie May        Rod Stewart    8.5  1990
8    9                   Romanza     Andrea Bocelli   10.8  1996
9   10  When a man loves a woman       Percy Sledge    8.7  1987
10  11               Black angel        Savage Rose   10.9  1995
11  12      1999 Grammy Nominees               Many   10.2  1999
12  13        For the good times       Kenny Rogers    8.7  1995
13  14          Big Willie style         Will Smith    9.9  1997
14  15              Tupelo Honey       Van Morrison    8.2  1971
15  16                Soulsville          Jorn Hoel    7.9  1996
16  17          The very best of        Cat Stevens    8.9  1990
17  18                      Stop          Sam Brown    8.9  1988
18  19           Bridge of Spies              T'Pau    7.9  1987
19  20            Private Dancer        Tina Turner    8.9  1983
20  21            Midt om natten         Kim Larsen    7.8  1983
21  22    Pavarotti Gala Concert  Luciano Pavarotti    9.9  1991
22  23       The dock of the bay       Otis Redding    7.9  1987
23  24              Picture book         Simply Red    7.2  1985
24  25                       Red     The Communards    7.8  1987
25  26          Unchain my heart         Joe Cocker    8.2  1987