In [31]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Introduction to Pandas (Data Frames)
## Econ 5015

These slides present an introduction to some key data structures available in the Pandas module.

In particular, the DataFrame structure is a key data type for storing structured data for the purpose of data analysis.

At first, we will not explore all the features available, in order to keep things simple.

### Series

Series is an object in Pandas that is an indexed, one-dimensional array.

The difference between a Series and the arrays from NumPy is that there is an explicit Index. 

The default Index, however, is the same as what we used to index arrays: a sequence of integers starting at 0.

In the example on the next slide, note that I am using the alias pd for pandas (for convenience).

In [32]:
import numpy as np
import pandas as pd
s = pd.Series([1,3,5,7,9])
s

0    1
1    3
2    5
3    7
4    9
dtype: int64

Compared to an array, note that there are two columns.  The first column is the Index column.  The second column is the actual data (i.e. the array).

In general, the explicit Index associated with a Series can complicate the syntax for selecting specific elements from a Series.

For now, though, since we are using the default Index, everything is roughly the same as with an array (except for the negative index case).

In [33]:
s[0]
s[4]
s[1:3]
s[0:5:2]
s[:3]

np.int64(1)

np.int64(9)

1    3
2    5
dtype: int64

0    1
2    5
4    9
dtype: int64

0    1
1    3
2    5
dtype: int64

In [34]:
s[2:]
s[[1,3]]
s[[True,False,True,True,False]]
# s[-1]  does not work

2    5
3    7
4    9
dtype: int64

1    3
3    7
dtype: int64

0    1
2    5
3    7
dtype: int64

Now let's create some Series with other indexes.  In pd.Series below, the first argument is the data and the second argument is the index.

In [35]:
uptolow = pd.Series(["a","b","c","d"],["A","B","C","D"])
uptolow
uptolow["C"]
uptolow["A":"C"]   #note that final index "C" is included
uptolow[["A","C"]]

A    a
B    b
C    c
D    d
dtype: object

'c'

A    a
B    b
C    c
dtype: object

A    a
C    c
dtype: object

What if a Series has integer indexes but not the default (implicit) indexes?

Some confusing things. If you provide a single index, the explicit index is used. If you provide a slice (using :) then implicit indexes are used.

In [36]:
s = pd.Series([1,3,5,7,9],[1,2,3,4,5])
s
s[3]  #explicit index 3
s[1:3]  #implicit index 1 and 2 (3 excluded)

1    1
2    3
3    5
4    7
5    9
dtype: int64

np.int64(5)

2    3
3    5
dtype: int64

This is certainly very confusing, so it is best practice not to index Series in the ways shown above.

To alleviate this confusion, use loc[] to use explicit index and iloc[] to use implicit index.

By using loc and iloc, you clearly indicate which type of indexing you are intending to use, which makes your code much clearer.  I recommend using loc or iloc even in the case where the index is not integers (like the uptolow example above).

In [37]:
s[3]
s.loc[3]  #explicit index 3
s.iloc[3] #implicit index 3
s[1:3]
s.loc[1:3]  #explicit index 1 2 and 3
s.iloc[1:3] #implicit index 1 and 2
s[[2,4]]
s.loc[[2,4]]
s.iloc[[2,4]]

np.int64(5)

np.int64(5)

np.int64(7)

2    3
3    5
dtype: int64

1    1
2    3
3    5
dtype: int64

2    3
3    5
dtype: int64

2    3
4    7
dtype: int64

2    3
4    7
dtype: int64

3    5
5    9
dtype: int64

### DataFrames

DataFrames are like spreadsheets.  They have rows and (named) columns.  Each column is a Series.  Each Series (column) shares the same Index.

All elements in a column are of the same data type (since columns are a Series).

Different columns can have different data types.  Every column has the same length.

This format is helpful for standard data anaysis and econometrics.  You can think of the rows as the observations and the columns as the variables.  For example, if we have daily weather data for a year, then a DataFrame may have columns for hightemp, lowtemp, precip, and wind and 365 rows (one for each day in the year).

In the example below, we will create a DataFrame with 2 columns:  the first 26 positive integers and the 26 lower case letters.

In [38]:
num=np.arange(1,27,1)
num
let=np.array(list("abcdefghijklmnopqrstuvwxyz"))
let
df=pd.DataFrame({"numbers": num,"letters": let})

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26])

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
       'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype='<U1')

In [39]:
df

    numbers letters
0         1       a
1         2       b
2         3       c
3         4       d
4         5       e
5         6       f
6         7       g
7         8       h
8         9       i
9        10       j
10       11       k
11       12       l
12       13       m
13       14       n
14       15       o
15       16       p
16       17       q
17       18       r
18       19       s
19       20       t
20       21       u
21       22       v
22       23       w
23       24       x
24       25       y
25       26       z

Note that I created the data frame from two arrays, although I could have created num and let as Series instead of arrays.

Python automatically converts the array to a Series (using default Index), and if I reference one column of the data frame, it is of type Series.

You can reference a column of a data frame in two ways, shown below.

In [40]:
type(df)
type(df.letters)

pandas.core.frame.DataFrame

pandas.core.series.Series

In [41]:
df.letters

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: letters, dtype: object

In [42]:
df['letters']

0     a
1     b
2     c
3     d
4     e
5     f
6     g
7     h
8     i
9     j
10    k
11    l
12    m
13    n
14    o
15    p
16    q
17    r
18    s
19    t
20    u
21    v
22    w
23    x
24    y
25    z
Name: letters, dtype: object

In [43]:
df.letters.iloc[0]
df.letters.iloc[10]
df.numbers.iloc[0]
df.numbers.iloc[25]
df.numbers.iloc[1:4]
df.letters.iloc[::2]

'a'

'k'

np.int64(1)

np.int64(26)

1    2
2    3
3    4
Name: numbers, dtype: int64

0     a
2     c
4     e
6     g
8     i
10    k
12    m
14    o
16    q
18    s
20    u
22    w
24    y
Name: letters, dtype: object

To select multiple rows of a data frame, we can index in the normal way.

In [44]:
df.iloc[1:11]  #selects rows 1-10

    numbers letters
1         2       b
2         3       c
3         4       d
4         5       e
5         6       f
6         7       g
7         8       h
8         9       i
9        10       j
10       11       k

To select a single row from data frame, follow above example but select a single row.  This evaluates to a DataFrame with only one row.

If you want to select a single row as an array (rather than as a DataFrame), see next slide.

In [45]:
df.iloc[2:3]  #second row as DataFrame

   numbers letters
2        3       c

### Other attributes of DataFrames

You can think of a DataFrame as 2-dimensional array where the columns have names and the rows have names (or indices).  So, a DataFrame can be deconstructed into the values (the 2-dimensional array), the columns names, and the row indices.

The "values" attribute gets a representation of the data frame as a 2-dimensional array (omitting columns names and row indices).

A single entry in a 2-dimensional array can be indexed as [r,c] where r is the row and c the column. 

[r] yields the r-th row

[:,c] yields the c-th column

In [46]:
type(df.values)
df.values[2,1]  #second row, first column
df.values[2]  #second row
df.values[:,1]  #first column

numpy.ndarray

'c'

array([3, 'c'], dtype=object)

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
       'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype=object)

The "columns" attribute is of type Index and has all the column names.

You can reference specific elements of this Index (i.e. specific column names) in the same way as an array.

In [47]:
df.columns
np.array(df.columns)  #change type to be array
df.columns[1]

Index(['numbers', 'letters'], dtype='object')

array(['numbers', 'letters'], dtype=object)

'letters'

The "index" attribute is of type Index and has all the row indices.

In [48]:
df.index
df.index[2]
df.index[0:5]
np.array(df.index[0:5])

RangeIndex(start=0, stop=26, step=1)

2

RangeIndex(start=0, stop=5, step=1)

array([0, 1, 2, 3, 4])

### Adding and removing a column to a DataFrame

In [49]:
df["negative"]=np.arange(-1,-27,-1)
df

    numbers letters  negative
0         1       a        -1
1         2       b        -2
2         3       c        -3
3         4       d        -4
4         5       e        -5
5         6       f        -6
6         7       g        -7
7         8       h        -8
8         9       i        -9
9        10       j       -10
10       11       k       -11
11       12       l       -12
12       13       m       -13
13       14       n       -14
14       15       o       -15
15       16       p       -16
16       17       q       -17
17       18       r       -18
18       19       s       -19
19       20       t       -20
20       21       u       -21
21       22       v       -22
22       23       w       -23
23       24       x       -24
24       25       y       -25
25       26       z       -26

In [50]:
df["mult"]=df.numbers*df.negative
df

    numbers letters  negative  mult
0         1       a        -1    -1
1         2       b        -2    -4
2         3       c        -3    -9
3         4       d        -4   -16
4         5       e        -5   -25
5         6       f        -6   -36
6         7       g        -7   -49
7         8       h        -8   -64
8         9       i        -9   -81
9        10       j       -10  -100
10       11       k       -11  -121
11       12       l       -12  -144
12       13       m       -13  -169
13       14       n       -14  -196
14       15       o       -15  -225
15       16       p       -16  -256
16       17       q       -17  -289
17       18       r       -18  -324
18       19       s       -19  -361
19       20       t       -20  -400
20       21       u       -21  -441
21       22       v       -22  -484
22       23       w       -23  -529
23       24       x       -24  -576
24       25       y       -25  -625
25       26       z       -26  -676

In [51]:
df=df.drop("mult",axis="columns")  #df.drop is creating a new dataframe which is then saved under the same variable name
df

    numbers letters  negative
0         1       a        -1
1         2       b        -2
2         3       c        -3
3         4       d        -4
4         5       e        -5
5         6       f        -6
6         7       g        -7
7         8       h        -8
8         9       i        -9
9        10       j       -10
10       11       k       -11
11       12       l       -12
12       13       m       -13
13       14       n       -14
14       15       o       -15
15       16       p       -16
16       17       q       -17
17       18       r       -18
18       19       s       -19
19       20       t       -20
20       21       u       -21
21       22       v       -22
22       23       w       -23
23       24       x       -24
24       25       y       -25
25       26       z       -26

### Adding and removing rows

To add rows, we will use the concat function in pandas.  We create a new dataframe with the new rows using pd.DataFrame and then concat the old dataframe and new dataframe.  

The concat function creates a new data frame (i.e. does not modify the input dataframes).  

Use ignore_index=True if using concat as shown below.

In [52]:
df=pd.concat([df,pd.DataFrame({"numbers":[27],"letters": ["aa"],"negative": [-27]})],ignore_index=True)
df

    numbers letters  negative
0         1       a        -1
1         2       b        -2
2         3       c        -3
3         4       d        -4
4         5       e        -5
5         6       f        -6
6         7       g        -7
7         8       h        -8
8         9       i        -9
9        10       j       -10
10       11       k       -11
11       12       l       -12
12       13       m       -13
13       14       n       -14
14       15       o       -15
15       16       p       -16
16       17       q       -17
17       18       r       -18
18       19       s       -19
19       20       t       -20
20       21       u       -21
21       22       v       -22
22       23       w       -23
23       24       x       -24
24       25       y       -25
25       26       z       -26
26       27      aa       -27

In [53]:
df=df.drop(3)
df

    numbers letters  negative
0         1       a        -1
1         2       b        -2
2         3       c        -3
4         5       e        -5
5         6       f        -6
6         7       g        -7
7         8       h        -8
8         9       i        -9
9        10       j       -10
10       11       k       -11
11       12       l       -12
12       13       m       -13
13       14       n       -14
14       15       o       -15
15       16       p       -16
16       17       q       -17
17       18       r       -18
18       19       s       -19
19       20       t       -20
20       21       u       -21
21       22       v       -22
22       23       w       -23
23       24       x       -24
24       25       y       -25
25       26       z       -26
26       27      aa       -27

In [54]:
df=df.reset_index(drop=True)
df

    numbers letters  negative
0         1       a        -1
1         2       b        -2
2         3       c        -3
3         5       e        -5
4         6       f        -6
5         7       g        -7
6         8       h        -8
7         9       i        -9
8        10       j       -10
9        11       k       -11
10       12       l       -12
11       13       m       -13
12       14       n       -14
13       15       o       -15
14       16       p       -16
15       17       q       -17
16       18       r       -18
17       19       s       -19
18       20       t       -20
19       21       u       -21
20       22       v       -22
21       23       w       -23
22       24       x       -24
23       25       y       -25
24       26       z       -26
25       27      aa       -27

### Importing Data

Typically, we don’t create a data frame directly, but import data from another source.

For example:  CSV files (comma separated values)

CSV is a text-based representation of spreadsheet data.

Each row of a spreadsheet is one line of a csv file.

Each cell in a row is separated by a comma.

Often the first row has the column names.

### CSV Example

id,year,income

1,1993, 55000

2,1994, 60000

3,1995, 62000

### Importing CSV

In [55]:
yhoo=pd.read_csv("yhoo.csv")
yhoo.values[0,]
yhoo

array(['8-Oct-14', 41.0, 41.29, 40.1, 41.08, '26,571,400', 41.08],
      dtype=object)

,Date,Open,High,Low,Close,Volume,Adj Close*
0,8-Oct-14,41.00,41.29,40.10,41.08,"26,571,400",41.08
1,7-Oct-14,41.06,41.29,40.78,40.93,"22,519,300",40.93
2,6-Oct-14,41.20,41.73,41.04,41.52,"23,552,300",41.52
3,3-Oct-14,40.79,41.69,40.65,41.03,"38,173,300",41.03
4,2-Oct-14,40.24,40.64,39.69,40.50,"24,584,400",40.50
...,...,...,...,...,...,...,...
62,11-Jul-14,34.95,35.56,34.78,35.43,"18,379,500",35.43
63,10-Jul-14,34.33,34.97,34.10,34.93,"18,064,800",34.93
64,9-Jul-14,34.68,35.07,34.68,34.85,"12,626,900",34.85
65,8-Jul-14,35.64,35.66,34.28,34.53,"23,096,900",34.53
66,* Close price adjusted for dividends and splits.,NaN,NaN,NaN,NaN,NaN,NaN

Note that the last row is not data, it's a footnote.  We want to delete it before we use the DataFrame for data analysis.

In [56]:
yhoo=yhoo.drop(66)
yhoo
np.max(yhoo.High)
np.min(yhoo.Low)
np.max(yhoo.Volume)
np.min(yhoo.Volume)
np.max(yhoo.Open)
np.min(yhoo.Open)

         Date   Open   High    Low  Close      Volume  Adj Close*
0    8-Oct-14  41.00  41.29  40.10  41.08  26,571,400       41.08
1    7-Oct-14  41.06  41.29  40.78  40.93  22,519,300       40.93
2    6-Oct-14  41.20  41.73  41.04  41.52  23,552,300       41.52
3    3-Oct-14  40.79  41.69  40.65  41.03  38,173,300       41.03
4    2-Oct-14  40.24  40.64  39.69  40.50  24,584,400       40.50
..        ...    ...    ...    ...    ...         ...         ...
61  14-Jul-14  35.80  35.95  35.45  35.70  18,680,500       35.70
62  11-Jul-14  34.95  35.56  34.78  35.43  18,379,500       35.43
63  10-Jul-14  34.33  34.97  34.10  34.93  18,064,800       34.93
64   9-Jul-14  34.68  35.07  34.68  34.85  12,626,900       34.85
65   8-Jul-14  35.64  35.66  34.28  34.53  23,096,900       34.53

[66 rows x 7 columns]

np.float64(44.01)

np.float64(32.93)

'93,321,700'

'10,593,700'

np.float64(43.98)

np.float64(33.18)